language: ruby
sudo: true
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.3.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.4.3.deb
  - sudo service elasticsearch restart
  - rm Gemfile.lock
  - mv Gemfile.travis Gemfile
script:
  - cd test/dummy && bundle exec rake db:create db:migrate
  - cd ../.. && bundle exec rake test
env:
  - RAILS=5.1
rvm:
  - 2.2.2
  - 2.3.0
  - 2.4.0
matrix:
  fast_finish: true
services:
  - postgresql
notifications:
  email: false
